### ISSUE TITLE
PHPMailer configuration is not persistent

### ISSUE THREAD

**Issue by maxguru** [RedpointGames/phabricator#71]
PHPMailer host/user/pass configuration is stored in /srv/phabricator/phabricator/conf/local/local.json (requires CLI usage to set).  It is not persistent across container rebuilds.  I can't seem to find any docs on how to set email configuration using environment variables.

**Comment by hach-que** [comment]
It's best to use a custom script for things like this: https://github.com/RedpointGames/phabricator/blob/master/ADVANCED-CONFIG.md#running-custom-commands-during-the-boot-process

We can't have an environment variable for every Phabricator option, especially since they appear and disappear over time, and our environment variable list would quickly get out of date.

**Comment by maxguru** [comment]
Ya but it is such a chore to mess around with scripts and volumes...  Env vars are quick and easy..
